spring:
  profiles:
    active: dev
  redis:
    host: 42.194.207.215
    port: 16379
    password: ldl5463

upload:
  maxsize: 2
  filenamelength: 500
vsftpd:
  host: 42.194.207.215
  port: 21
  username: test
  password: test
